export const fuzzy_skills = [
    // Management-based skills
    "Leadership",
    "Strategic thinking",
    "Communication",
    "Project management",
    "Team building",
    "Decision making",
    "Time management",
    "Problem solving",
    "Interpersonal skills",
    "Adaptability",
    "Collaboration",
    "Creativity",
    "Conflict resolution",
    "Emotional intelligence",
    "Innovation",
    "Negotiation",
    "Performance management",
    "Planning and organization",
    "Resource management",
    "Stress management",
    "Training and development",
    "Vision setting",
    "Active listening",
    "Agile methodologies",

    // Technical-based skills
    "React",
    "Angular",
    "Vue",
    "Node.js",
    "Python",
    "Java",
    "JavaScript",
    "HTML",
    "CSS",
    "Artificial Intelligence",
    "Big data",
    "Business intelligence",
    "Computer graphics",
    "Content management systems",
    "DevOps",
    "E-commerce",
    "Enterprise resource planning (ERP)",
    "Geographic Information Systems (GIS)",
    "Internet of Things (IoT)",
    "Operating systems",
    "Search engine optimization (SEO)",
    "Social media management",
    "Software development",
    "Web design",
    "Web development",
    "Amazon Web Services (AWS)",
    "Analytical",
    "Android development",
    "Apache Hadoop",
    "API development",
    "ASP.NET",
    "Automation",
    "Back-end development",
    "Blockchain",
    "C#",
    "C++",
    "Cloud architecture",
    "Cloud security",
    "Cloud storage",
    "Code review",
    "Coding standards",
    "Content creation",
    "Continuous integration",
    "Cryptocurrency",
    "Customer service",
    "Data analysis",
    "Data engineering",
    "Data management",
    "Data mining",
    "Data modeling",
    "Data science",
    "Data warehousing",
    "Debugging",
    "Design patterns",
    "Distributed systems",
    "Documentation",
    "Embedded systems",
    "Express.JS",
    "Front-end development",
    "Functional programming",
    "Game development",
    "Git",
    "Go",
    "GraphQL",
    "iOS development",
    "Jenkins",
    "jQuery",
    "Kubernetes",
    "Linux",
    "Machine learning",
    "MapReduce",
    "MERN",
    "Microsoft Azure",
    "Mobile development",
    "MONGO DB",
    "MySQL",
    "Node.JS",
    "Network protocols",
    "NoSQL",
    "Object-oriented programming",
    "Open source",
    "Performance optimization",
    "PHP",
    "PostgreSQL",
    "Product management",
    "Programming paradigms",
    "Quality assurance",
    "RESTful API design",
    "Ruby",
    "Ruby on Rails",
    "Scalability",
    "Scala",
    "Security",
    "Serverless architecture",
    "SOAP",
    "Software architecture",
    "Software testing",
    "SQL",
    "Swift",
    "System administration",
    "User experience design",
    "User interface design",
    "Version control",
    "Virtualization",
    "Visual design",
    "Windows Server"
];